import { HttpStatus } from '@nestjs/common';

export const enum HttpStatusConst {
  OK = HttpStatus.OK,
  CREATED = HttpStatus.CREATED,
  BAD_REQUEST = HttpStatus.BAD_REQUEST,
  UNAUTHORIZED = HttpStatus.UNAUTHORIZED,
  FORBIDDEN = HttpStatus.FORBIDDEN,
  INTERNAL_SERVER_ERROR = HttpStatus.INTERNAL_SERVER_ERROR,
  TOO_MANY_REQUESTS = HttpStatus.TOO_MANY_REQUESTS,
  NOT_FOUND = HttpStatus.NOT_FOUND,
  CONFLICT = HttpStatus.CONFLICT,
  GONE = HttpStatus.GONE,
  PAYLOAD_TOO_LARGE = HttpStatus.PAYLOAD_TOO_LARGE,
  UNSUPPORTED_MEDIA_TYPE = HttpStatus.UNSUPPORTED_MEDIA_TYPE,
  NOT_ACCEPTABLE = HttpStatus.NOT_ACCEPTABLE,
  PRECONDITION_FAILED = HttpStatus.PRECONDITION_FAILED,
}
